<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Lite.Procedures</RootNamespace>
        <IsPackable>true</IsPackable>
        <Description>Synchronous procedure pipeline for Lite.Procedures (thread-based, no async).</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lite.Procedures.Abstractions\Lite.Procedures.Abstractions.csproj" />
    </ItemGroup>

</Project>
