<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <Description>Async procedure pipeline runtime for Lite.Procedures.</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lite.Procedures.Abstractions\Lite.Procedures.Abstractions.csproj" />
    </ItemGroup>

</Project>
