using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lite.Procedures.Rpc.SourceGenerators
{
    /// <summary>
    /// Emits a single <c>RpcProvider</c> per assembly: it collects every procedure tagged with
    /// <c>[Rpc]</c>, builds an <c>RpcDescriptor</c> array (AoT-safe closed-generic <c>typeof</c>), and
    /// registers the provider into <c>RpcRegistry</c> through a <c>[ModuleInitializer]</c> — mirroring
    /// the pipeline-factory generator.
    /// </summary>
    [Generator]
    public sealed class RpcProviderGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var rpcs = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is ClassDeclarationSyntax c
                        && c.AttributeLists.Count > 0
                        && !c.Modifiers.Any(static m => m.ValueText == "abstract"),
                    transform: TryExtract)
                .Where(static r => r is not null)
                .Select(static (r, _) => r!)
                .Collect();

            context.RegisterSourceOutput(rpcs, Emit);
        }

        private static RpcInfo? TryExtract(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node, ct) is not INamedTypeSymbol symbol)
                return null;

            if (symbol.IsAbstract || symbol.IsStatic || symbol.IsGenericType || symbol.TypeKind != TypeKind.Class)
                return null;

            // Require the [Rpc] attribute from this package.
            AttributeData? rpc = null;
            foreach (var attr in symbol.GetAttributes())
            {
                var ac = attr.AttributeClass;
                if (ac == null) continue;
                if (ac.Name == "RpcAttribute" && ac.ContainingNamespace?.ToDisplayString() == "Lite.Procedures.Rpc")
                {
                    rpc = attr;
                    break;
                }
            }
            if (rpc == null) return null;

            // The argument/result types come from IAsyncProcedure<TArgs,TResult>.
            ITypeSymbol? argType = null, resultType = null;
            foreach (var iface in symbol.AllInterfaces)
            {
                if (iface.TypeArguments.Length != 2) continue;
                var def = iface.OriginalDefinition;
                if (def.ContainingNamespace.ToDisplayString() == "Lite.Procedures" && def.Name == "IAsyncProcedure")
                {
                    argType = iface.TypeArguments[0];
                    resultType = iface.TypeArguments[1];
                    break;
                }
            }
            if (argType == null || resultType == null) return null;

            // Generated provider is top-level in this assembly; it can only reference assembly-visible types.
            if (!IsAssemblyVisible(symbol) || !IsAssemblyVisible(argType) || !IsAssemblyVisible(resultType))
                return null;

            string? Named(string name)
            {
                foreach (var na in rpc.NamedArguments)
                    if (na.Key == name && na.Value.Value is string s)
                        return s;
                return null;
            }

            return new RpcInfo(
                symbol, argType, resultType,
                service: Named("Service"),
                method: Named("Method"),
                package: Named("Package"),
                version: Named("Version"),
                schemes: Named("Schemes"));
        }

        private static void Emit(SourceProductionContext context, ImmutableArray<RpcInfo> rpcs)
        {
            if (rpcs.IsDefaultOrEmpty) return;

            var unique = rpcs
                .GroupBy(static r => r.Procedure, SymbolEqualityComparer.Default)
                .Select(static g => g.First())
                .ToList();

            var fq = SymbolDisplayFormat.FullyQualifiedFormat;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            sb.AppendLine("namespace Lite.Procedures.Rpc.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal sealed class RpcProvider : global::Lite.Procedures.Rpc.IRpcProvider");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly global::Lite.Procedures.Rpc.RpcDescriptor[] _descriptors = new global::Lite.Procedures.Rpc.RpcDescriptor[]");
            sb.AppendLine("        {");
            foreach (var r in unique)
            {
                var argFqn = r.Argument.ToDisplayString(fq);
                var resFqn = r.Result.ToDisplayString(fq);
                var procFqn = r.Procedure.ToDisplayString(fq);
                var service = Literal(r.Service ?? r.Procedure.Name);
                var method = Literal(r.Method ?? r.Procedure.Name);
                var package = r.Package == null ? "null" : Literal(r.Package);
                var version = r.Version == null ? "null" : Literal(r.Version);
                var schemes = SchemesLiteral(r.Schemes);
                sb.Append("            new global::Lite.Procedures.Rpc.RpcDescriptor(")
                  .Append($"typeof({argFqn}), typeof({resFqn}), {service}, {method}, {package}, {version}, {schemes}, typeof({procFqn})),")
                  .AppendLine();
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::Lite.Procedures.Rpc.RpcDescriptor> Descriptors => _descriptors;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class RpcProviderRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void Register()");
            sb.AppendLine("            => global::Lite.Procedures.Rpc.RpcRegistry.Register(new RpcProvider());");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("LiteProceduresRpcGenerated.g.cs", sb.ToString());
        }

        // Schemes is a CSV string ("membership" / "membership,public"); emit a string[] literal.
        private static string SchemesLiteral(string? schemes)
        {
            if (string.IsNullOrWhiteSpace(schemes))
                return "global::System.Array.Empty<string>()";

            var parts = schemes!
                .Split(new[] { ',', ';' })
                .Select(static s => s.Trim())
                .Where(static s => s.Length > 0)
                .ToList();

            if (parts.Count == 0)
                return "global::System.Array.Empty<string>()";

            return "new string[] { " + string.Join(", ", parts.Select(Literal)) + " }";
        }

        private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

        private static bool IsAssemblyVisible(ITypeSymbol? type)
        {
            switch (type)
            {
                case null:
                    return false;
                case IArrayTypeSymbol array:
                    return IsAssemblyVisible(array.ElementType);
                case INamedTypeSymbol named:
                    for (var current = named; current != null; current = current.ContainingType)
                    {
                        switch (current.DeclaredAccessibility)
                        {
                            case Accessibility.Public:
                            case Accessibility.Internal:
                            case Accessibility.ProtectedOrInternal:
                                break;
                            default:
                                return false;
                        }
                    }

                    foreach (var argument in named.TypeArguments)
                        if (!IsAssemblyVisible(argument))
                            return false;

                    return true;
                default:
                    return true;
            }
        }

        private sealed class RpcInfo
        {
            public RpcInfo(
                INamedTypeSymbol procedure, ITypeSymbol argument, ITypeSymbol result,
                string? service, string? method, string? package, string? version, string? schemes)
            {
                Procedure = procedure;
                Argument = argument;
                Result = result;
                Service = service;
                Method = method;
                Package = package;
                Version = version;
                Schemes = schemes;
            }

            public INamedTypeSymbol Procedure { get; }
            public ITypeSymbol Argument { get; }
            public ITypeSymbol Result { get; }
            public string? Service { get; }
            public string? Method { get; }
            public string? Package { get; }
            public string? Version { get; }
            public string? Schemes { get; }
        }
    }
}
